### ISSUE TITLE
Can't get slider to slide one image at a time

### ISSUE THREAD

**Issue by kidcodester** [Eastros/FrameCarousel#4] opened 2017-05-02 15:46 UTC
Hello,

I copied the dist folder and renamed it as frame-carousel, per your instructions.

After resolving the directory issue (had to modify variable 'dirSample' in jquery.frame-carousel.js), I was finally able to get the frame.png and sample images loaded but they all appear at the same time with their widths set to 1/n (n = number of images) so in this case 10% with the scrolling advancing 10% into white space.

By modifying 
```
$('<div/>') -> width: 100% from width: 100 / this.options.images.length + '%'
```
I was able to get to the first slide to load but it does not load the next image and goes to blank slide, instead.

Any guidance on making 1 image appear at a time and for sliding to work correctly would be greatly appreciated.

**Comment by umarashfaq** [comment] 2017-05-02 15:55
Can you share a screenshot of how it looks? Also let me know the what browser/OS you're using

**Comment by kidcodester** [comment] 2017-05-02 16:54
Hello and thank you for your prompt response.

Here is what I get by default (with simple directory change to source the images):

![default](https://cloud.githubusercontent.com/assets/25160057/25628875/c1741e22-2f35-11e7-9e2c-c219b4316881.png)

This is what appears if I click on the right button to advance:

![defaultadv1](https://cloud.githubusercontent.com/assets/25160057/25628914/db9ba6f8-2f35-11e7-8799-06e5577fdbbd.png)

Here's what I'm able to get if I make the edits:

```
distance: n * (100 / this.elements.$images.length)
to
distance: n * (100/1)

and

width: 100 / this.options.images.length + '%',

to

width: '100%'
```

![modified](https://cloud.githubusercontent.com/assets/25160057/25629025/228848dc-2f36-11e7-9a27-4c18f3b5d739.png)

and advancing the modified by 1:

![modifiedadv1](https://cloud.githubusercontent.com/assets/25160057/25629035/2dccd29e-2f36-11e7-97c7-a25c73a9a016.png)

Of course, my edits are just a hack - so apologies for that.

I am using Chrome on Windows 10.

I hope this helps - let me know if I an provide you with anything else, as I find frame-carousel to be quite a nice presentation.

Thanks!

**Comment by umarashfaq** [comment] 2017-05-02 17:53
So you're saying the problem appeared after you changed the image source directory. My hunch is it must be something around the configurations. Is it possible to share your code/directories so I can have a look?

**Comment by kidcodester** [comment] 2017-05-02 18:47
Interesting...I was just putting together a stripped down version of my project to load here and I noticed that when I removed my project-specific css, the images loaded as they should.

I will see if I can track down the offending element(s) to see what might be interfering with FrameCarousel's behavior and will report back my findings.

**Comment by umarashfaq** [comment] 2017-05-02 19:03
Yes, please let me know if you're able to find the root cause.

**Comment by kidcodester** [comment] 2017-05-02 19:17
I believe I identified what was interfering.

I am using bootstrap and some other custom css but the main idea is I'm invoking webkit-box-sizing and flex-wrap:wrap to help align my elements, e.g.:

```
* {
    -webkit-box-sizing: border-box;
    -moz-box-sizing: border-box;
    -ms-box-sizing: border-box;
    box-sizing: border-box;    
    flex-wrap: wrap;
}

  img
, embed
, object
, video {
  max-width: 100%;
}
```

For some reason (though I cannot tell why now) I had the following in my css:

```
div {
   max-width: 100%;
}
```

If I remove this/comment it out, the images appear one at a time in the slider and the buttons cause the slider to progress correctly to the next image.

It's very likely something else is coming into play but at least in this one instance, doing without this selector/attribute seems to prevent the observed behavior.

**Comment by umarashfaq** [comment] 2017-05-03 06:58
Yes, it should be it. We have an element in the system called fc-film whose width is supposed to be n * 100%, where n is number of images. So this rule must be interfering with that.

Closing this issue, as I don't see anything to be done in FrameCarousel source code.

**Closed as completed by umarashfaq** 2017-05-03 06:58 UTC
